[package]
name = "std"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
syscall_macro = { path = "../syscall_macro", features = ["user"] }
syscalls = { path = "../syscalls", features = ["user"] }
